title: Jake Park
url: "https://jakepark.me"
timezone: Australia/Melbourne
collections:
  essays:
    output: true
    permalink: /essays/:name/
markdown: kramdown
kramdown:
  auto_ids: true
  header_links: true
